### ISSUE TITLE
Conditional disable stuff

### ISSUE THREAD

**Issue by ibes** [wordplate/plate#10]
Hi there,

Is it possible to conditionally disable stuff?
Eg. if the user is editor or administrator?

If I see it right that should work as known from all other places in WP, right?

**Comment by vinkla** [comment]
> Is it possible to conditionally disable stuff… …if I see it right that should work as known from all other places in WP, right?



This is possible with the [`current_user_can`](https://developer.wordpress.org/reference/functions/current_user_can/) function. Wrap it around code the `add_theme_support` functions. Let me know if you have any other questions!
