### ISSUE TITLE
[Question] Would this be possible to use outside of WordPlate?

### ISSUE THREAD

**Issue by jpmurray** [wordplate/plate#13]
If I wanted to include this in a template where I can't make use of WordPlate, would it work? Or is it dependent on WordPlate somehow?

**Comment by vinkla** [comment]
Yes, there are no requirements of WordPlate framework. You’ll only need to add the features in your `functions.php` file.

**Comment by jpmurray** [comment]
Excellent, I'll be doing that soon! I'd rather still use WordPlate as a whole, but, decisions where made... ;-)

Thank you!
