### ISSUE TITLE
Remove 'Format' panel from editor

### ISSUE THREAD

**Issue by elliottmangham** [wordplate/plate#5]
Hi,

I don't see an option to remove the Format panel form the Editor using `add_theme_support('plate-editor'`. Can you add this ability and/or advise?

Great job! Thank you.

**Comment by puredazzle** [comment]
Hi @elliottmangham, correct me if I am wrong, but don't you enable the formats dropdown for the posts manually via for example functions.php? I guess we are talking about https://codex.wordpress.org/Post_Formats

**Comment by elliottmangham** [comment]
Hi @puredazzle, you're right. My apologies, I completely forgot I'd enabled it!
