### ISSUE TITLE
Hide menu items from all users except specified

### ISSUE THREAD

**Issue by elliottmangham** [wordplate/plate#6]
Hi,

I am using the following code to hide the specified menu items using `plate-menu` from the `example` user.

```php
/* Hide menu items */
$current_admin_username = wp_get_current_user()->user_login;
if ($current_admin_username != "example") {
	add_theme_support('plate-menu', [
		'options-general.php?page=menu_editor', // Admin Menu Editor
		'edit.php?post_type=acf-field-group', // Advanced Custom Fields
		'tools.php?page=velvet-blues-update-urls.php', // Permalinks
		'admin.php?page=amazon-s3-and-cloudfront' // S3
	]);
}
```

This does work for one, `edit.php?post_type=acf-field-group` which is the second in the array. However, the other three do not. Am I doing this wrong? Is there a simple solution to this?

Thank you in advance.

**Comment by vinkla** [comment]
Hmm, we better ask @fiskhandlarn who is the `plate-menu` wizard.

**Comment by fiskhandlarn** [comment]
It looks like some of these must be removed with [remove_submenu_page](https://codex.wordpress.org/remove_submenu_page) instead of [remove_menu_page](https://codex.wordpress.org/Function_Reference/remove_menu_page). I'll do a rewrite and look for `?` in the `plate-menu` items and send a PR!

**Comment by fiskhandlarn** [comment]
@vinkla This should fix the above issues: https://github.com/wordplate/plate/pull/7

**Comment by fiskhandlarn** [comment]
I have to test `'options-general.php?page=menu_editor'` though.

**Comment by fiskhandlarn** [comment]
Just tried it, `'options-general.php?page=menu_editor'` is also being hidden by the above PR.

**Comment by fiskhandlarn** [comment]
As soon as the PR is merged I'll update the project README as well.

**Comment by vinkla** [comment]
@fiskhandlarn thanks! I'll look at it asap.

**Comment by vinkla** [comment]
This is fixed in version [3.1.0](https://github.com/wordplate/plate/releases/tag/3.1.0).

**Comment by fiskhandlarn** [comment]
@elliottmangham FYI, I haven't tested this with your code for restricting certain users, but I'm guessing it will work anyways now (since the issue was present even without that restriction code). Pls report back if not working as expected.

**Comment by elliottmangham** [comment]
Hi @vinkla and @fiskhandlarn,

Thanks so much for investigating this and getting back to me.

It seems I can't update to the latest version of Plate. I'm stuck on 3.0.2, even if I download the latest zipped (3.1.0). I normally use Composer.

Is there something wrong with the this? Once I've got the latest I will be able to test.

😄

**Comment by vinkla** [comment]
@elliottmangham sorry, that was my fault. I forgot to bump the version number ¯⁠\_(ツ)_/⁠¯

Please try to update again.

**Comment by elliottmangham** [comment]
Hi @vinkla,

Ah, that explains it! Thank you.

I have tried your example code, and mine I wrote in the Issue and neither work, even on version 3.1.0.

Not sure why this wouldn't work.

Thanks again

**Comment by vinkla** [comment]
@elliottmangham if you visit the pages you want to hide in the browser. Could you copy and paste the URLs or permalinks?

**Comment by elliottmangham** [comment]
Hey @vinkla, sorry, I will get this over to you.

I also noticed there's no backward support as version 3.1.0 requires php ^7.1.3.

**Comment by vinkla** [comment]
Yeah, since we’re using Laravel and Symfony components we updated the PHP requirement.

**Comment by elliottmangham** [comment]
@vinkla, no worries!

Here's an example:

This works...
http://test-site.local/wp/wp-admin/index.php
http://test-site.local/wp/wp-admin/upload.php

Despite, this is my function:
```php
	add_theme_support('plate-disable-menu', [
	    'index.php', // dashboard
	    'upload.php', // media
	]);
```

Could it be related to the `/wp/wp-admin`? I have this, because I use [Bedrock](https://github.com/roots/bedrock).

**Comment by vinkla** [comment]
I guess it shouldn't be an issue with Bedrock + Plate. What is your opinion @fiskhandlarn?

**Comment by fiskhandlarn** [comment]
@vinkla I have no way of testing Bedrock, but I can't imagine it would be a problem.

@elliottmangham You have written `'plate-disable-menu'` in your example. Try with `'plate-menu'` instead, like this:

```
add_theme_support('plate-menu', [
    'index.php', // dashboard
    'upload.php', // media
]);
```

**Comment by elliottmangham** [comment]
Hi @fiskhandlarn & @vinkla,

I have tried with `add_theme_support('plate-menu', [` but it still has no effect. All the other functions work perfectly, it's only this that doesn't.

I hope I'm not stealing too much of your time!

Best,

**Comment by fiskhandlarn** [comment]
@elliottmangham You are using version 3.1.0 and the dashboard/media isn't hidden from the menu with code I provided in https://github.com/wordplate/plate/issues/6#issuecomment-369237821? If not, can you please provide a screenshot of your wp-admin including the menu?
